### ISSUE TITLE
Images are not restricted to 100% body width

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro-docs#28]
We need an

```css
img {
 width: 100%
}
```

somewhere so that on mobile it doesn't blow out the screen with overflow
